MINVOKER-140: additional note
apache/maven-invoker-plugin pull request #135
Opened 2022-07-26 16:28 UTC by bvfalcon

In Addition to MINVOKER-140: exclude patterns works only if one or more include pattern(s) exists. This is a feature of [plexus-utils Component DirectoryScanner](https://github.com/codehaus-plexus/plexus-utils/blob/3896620b4fbf031b1b02b4d46b328c5839a231da/src/main/java/org/codehaus/plexus/util/DirectoryScanner.java#L447-L449). 

So, in our case command line parameter <code>-Dinvoker.test=!testX</code> (and configuration parameter [invokerTest](https://maven.apache.org/plugins/maven-invoker-plugin/run-mojo.html#invokerTest) ) works absolutely different way: **all projects** (not only testX) will be skipped. We must use <code>-Dinvoker.test=\*,!testX</code> or <code>-Dinvoker.test=!testX,\*</code> as workarround.

In this commit I add forced additional include pattern "*" as default include patter for cases, if invoker.test contains only exclude-pattern. User still use <code>-Dinvoker.test=!testX</code> and all will work correctlz for him. The change has full back-compatibility with current plugin settings.

Integration test invocation-cmdline-exclude is actualized.

2022-07-26 17:40 UTC, slawekjaranowski requested changes
We change some of logic - please create new issue with description, examples and justifications

2022-07-26 17:40 UTC, slawekjaranowski commented on src/it/invocation-cmdline-exclude/src/it/minvoker-140-executable/pom.xml
> +        <version>1.1.1</version>
very old version 😄 pleas use the latest
please also update in `minvoker-140-ignorable/pom.xml`

2022-07-26 17:40 UTC, slawekjaranowski commented on src/it/invocation-cmdline-exclude/verify.bsh
> +/*
please use groovy

2022-07-26 18:28 UTC, bvfalcon commented
> We change some of logic - please create new issue with description, examples and justifications

This PR is only bugfix, it contains nothing new. Logic is the same - "all except testX", but syntax <code>-Dinvoker.test=!testX</code> not works and syntax <code>-Dinvoker.test=\*,!testX</code> not so obvious.

2022-07-26 21:59 UTC, slawekjaranowski commented
You are right it is a bug. 
Thanks for your efforts.

We need issues for tracking - what next release will contains.

You also remove default PR template, which contains some of formal information about contributing license - please restore at lest such information.

2022-07-26 23:17 UTC, bvfalcon commented
Done. Jira ticket created - [MINVOKER-306](https://issues.apache.org/jira/projects/MINVOKER/issues/MINVOKER-306) and pull request description modified to standard view

2022-07-29 19:05 UTC, slawekjaranowski approved these changes

2022-07-29 19:05 UTC, merged

2025-06-10 06:20 UTC, jira-importer commented
Resolve #439

2025-06-10 06:23 UTC, jira-importer commented
Resolve #525